[tool.black]
line-length = 120
extend-exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | venv
  | \.venv
  | output
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
