from pathlib import Path
from typing import Any

class MalformedClassException(Exception): ...

class Utf8Info:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def str_bytes(self) -> bytes: ...

class FieldrefInfo: ...
class MethodrefInfo: ...
class InterfaceMethodrefInfo: ...

class InsnInfo:
    @property
    def type(self) -> Any: ...
    @property
    def bytecode_offset(self) -> int: ...
    @property
    def opcode(self) -> int: ...
    @property
    def index(self) -> int | None: ...
    @property
    def value(self) -> int | None: ...
    @property
    def branch_offset(self) -> int | None: ...
    @property
    def count(self) -> int | None: ...
    @property
    def reserved(self) -> bytes | None: ...
    @property
    def atype(self) -> Any | None: ...
    @property
    def dimensions(self) -> int | None: ...
    @property
    def default(self) -> int | None: ...
    @property
    def npairs(self) -> int | None: ...
    @property
    def pairs(self) -> list[Any] | None: ...
    @property
    def low(self) -> int | None: ...
    @property
    def high(self) -> int | None: ...
    @property
    def offsets(self) -> list[int] | None: ...

class SourceFileAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def sourcefile_index(self) -> int: ...

class CodeAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def max_stack(self) -> int: ...
    @property
    def max_stacks(self) -> int: ...
    @property
    def max_locals(self) -> int: ...
    @property
    def code_length(self) -> int: ...
    @property
    def code(self) -> list[InsnInfo]: ...
    @property
    def exception_table_length(self) -> int: ...
    @property
    def exception_table(self) -> list[Any]: ...
    @property
    def attributes_count(self) -> int: ...
    @property
    def attributes(self) -> list[Any]: ...

class FieldInfo:
    @property
    def access_flags(self) -> Any: ...
    @property
    def name_index(self) -> int: ...
    @property
    def descriptor_index(self) -> int: ...
    @property
    def attributes_count(self) -> int: ...
    @property
    def attributes(self) -> list[Any]: ...

class MethodInfo:
    @property
    def access_flags(self) -> Any: ...
    @property
    def name_index(self) -> int: ...
    @property
    def descriptor_index(self) -> int: ...
    @property
    def attributes_count(self) -> int: ...
    @property
    def attributes(self) -> list[Any]: ...

class ClassFile:
    @property
    def magic(self) -> int: ...
    @property
    def minor_version(self) -> int: ...
    @property
    def major_version(self) -> int: ...
    @property
    def constant_pool_count(self) -> int: ...
    @property
    def constant_pool(self) -> list[Any | None]: ...
    @property
    def access_flags(self) -> Any: ...
    @property
    def this_class(self) -> int: ...
    @property
    def super_class(self) -> int: ...
    @property
    def interfaces_count(self) -> int: ...
    @property
    def interface_count(self) -> int: ...
    @property
    def interfaces(self) -> list[int]: ...
    @property
    def fields_count(self) -> int: ...
    @property
    def field_count(self) -> int: ...
    @property
    def fields(self) -> list[FieldInfo]: ...
    @property
    def methods_count(self) -> int: ...
    @property
    def method_count(self) -> int: ...
    @property
    def methods(self) -> list[MethodInfo]: ...
    @property
    def attributes_count(self) -> int: ...
    @property
    def attribute_count(self) -> int: ...
    @property
    def attributes(self) -> list[Any]: ...
    def to_bytes(self) -> bytes: ...

class ClassReader:
    @classmethod
    def from_bytes(cls, bytes_or_bytearray: bytes | bytearray) -> ClassReader: ...
    @classmethod
    def from_file(cls, path: str | Path) -> ClassReader: ...
    @property
    def class_info(self) -> ClassFile: ...

class ClassWriter:
    @staticmethod
    def write(classfile: ClassFile) -> bytes: ...

def backend_info() -> tuple[str, str, list[str]]: ...
