from __future__ import annotations

from collections.abc import Callable, Iterator
from pathlib import Path
from typing import Any

# =============================================================================
# Exception
# =============================================================================

class MalformedClassException(Exception): ...

# =============================================================================
# Constant Pool Entry Types
# =============================================================================

class Utf8Info:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def str_bytes(self) -> bytes: ...

class IntegerInfo:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def value_bytes(self) -> int: ...

class FloatInfo:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def value_bytes(self) -> int: ...

class LongInfo:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def high_bytes(self) -> int: ...
    @property
    def low_bytes(self) -> int: ...

class DoubleInfo:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def high_bytes(self) -> int: ...
    @property
    def low_bytes(self) -> int: ...

class ClassInfo:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def name_index(self) -> int: ...

class StringInfo:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def string_index(self) -> int: ...

class FieldrefInfo:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def class_index(self) -> int: ...
    @property
    def name_and_type_index(self) -> int: ...

class MethodrefInfo:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def class_index(self) -> int: ...
    @property
    def name_and_type_index(self) -> int: ...

class InterfaceMethodrefInfo:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def class_index(self) -> int: ...
    @property
    def name_and_type_index(self) -> int: ...

class NameAndTypeInfo:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def name_index(self) -> int: ...
    @property
    def descriptor_index(self) -> int: ...

class MethodHandleInfo:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def reference_kind(self) -> int: ...
    @property
    def reference_index(self) -> int: ...

class MethodTypeInfo:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def descriptor_index(self) -> int: ...

class DynamicInfo:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def bootstrap_method_attr_index(self) -> int: ...
    @property
    def name_and_type_index(self) -> int: ...

class InvokeDynamicInfo:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def bootstrap_method_attr_index(self) -> int: ...
    @property
    def name_and_type_index(self) -> int: ...

class ModuleInfo:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def name_index(self) -> int: ...

class PackageInfo:
    @property
    def index(self) -> int: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def tag(self) -> int: ...
    @property
    def name_index(self) -> int: ...

# =============================================================================
# Instructions
# =============================================================================

class MatchOffsetPair:
    @property
    def match(self) -> int: ...
    @property
    def offset(self) -> int: ...

class InsnInfo:
    @property
    def type(self) -> Any: ...
    @property
    def bytecode_offset(self) -> int: ...
    @property
    def opcode(self) -> int: ...
    @property
    def index(self) -> int | None: ...
    @property
    def value(self) -> int | None: ...
    @property
    def branch_offset(self) -> int | None: ...
    @property
    def count(self) -> int | None: ...
    @property
    def reserved(self) -> bytes | None: ...
    @property
    def atype(self) -> Any | None: ...
    @property
    def dimensions(self) -> int | None: ...
    @property
    def default(self) -> int | None: ...
    @property
    def npairs(self) -> int | None: ...
    @property
    def pairs(self) -> list[MatchOffsetPair] | None: ...
    @property
    def low(self) -> int | None: ...
    @property
    def high(self) -> int | None: ...
    @property
    def offsets(self) -> list[int] | None: ...

class ExceptionInfo:
    @property
    def start_pc(self) -> int: ...
    @property
    def end_pc(self) -> int: ...
    @property
    def handler_pc(self) -> int: ...
    @property
    def catch_type(self) -> int: ...

# =============================================================================
# Attribute Types (lib.rs)
# =============================================================================

class ConstantValueAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def constantvalue_index(self) -> int: ...

class SignatureAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def signature_index(self) -> int: ...

class SourceFileAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def sourcefile_index(self) -> int: ...

class SourceDebugExtensionAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def debug_extension(self) -> bytes: ...

class ExceptionsAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def number_of_exceptions(self) -> int: ...
    @property
    def exception_index_table(self) -> list[int]: ...

class CodeAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def max_stack(self) -> int: ...
    @property
    def max_stacks(self) -> int: ...
    @property
    def max_locals(self) -> int: ...
    @property
    def code_length(self) -> int: ...
    @property
    def code(self) -> list[InsnInfo]: ...
    @property
    def exception_table_length(self) -> int: ...
    @property
    def exception_table(self) -> list[ExceptionInfo]: ...
    @property
    def attributes_count(self) -> int: ...
    @property
    def attributes(self) -> list[Any]: ...

class UnimplementedAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def info(self) -> bytes: ...

# =============================================================================
# Raw-Level Classes
# =============================================================================

class FieldInfo:
    @property
    def access_flags(self) -> Any: ...
    @property
    def name_index(self) -> int: ...
    @property
    def descriptor_index(self) -> int: ...
    @property
    def attributes_count(self) -> int: ...
    @property
    def attributes(self) -> list[Any]: ...

class MethodInfo:
    @property
    def access_flags(self) -> Any: ...
    @property
    def name_index(self) -> int: ...
    @property
    def descriptor_index(self) -> int: ...
    @property
    def attributes_count(self) -> int: ...
    @property
    def attributes(self) -> list[Any]: ...

class ClassFile:
    @property
    def magic(self) -> int: ...
    @property
    def minor_version(self) -> int: ...
    @property
    def major_version(self) -> int: ...
    @property
    def constant_pool_count(self) -> int: ...
    @property
    def constant_pool(self) -> list[Any | None]: ...
    @property
    def access_flags(self) -> Any: ...
    @property
    def this_class(self) -> int: ...
    @property
    def super_class(self) -> int: ...
    @property
    def interfaces_count(self) -> int: ...
    @property
    def interface_count(self) -> int: ...
    @property
    def interfaces(self) -> list[int]: ...
    @property
    def fields_count(self) -> int: ...
    @property
    def field_count(self) -> int: ...
    @property
    def fields(self) -> list[FieldInfo]: ...
    @property
    def methods_count(self) -> int: ...
    @property
    def method_count(self) -> int: ...
    @property
    def methods(self) -> list[MethodInfo]: ...
    @property
    def attributes_count(self) -> int: ...
    @property
    def attribute_count(self) -> int: ...
    @property
    def attributes(self) -> list[Any]: ...
    def to_bytes(self) -> bytes: ...

class ClassReader:
    def __init__(self, bytes_or_bytearray: bytes) -> None: ...
    @classmethod
    def from_bytes(cls, bytes_or_bytearray: bytes) -> ClassReader: ...
    @classmethod
    def from_file(cls, path: str | Path) -> ClassReader: ...
    @property
    def class_info(self) -> ClassFile: ...

class ClassWriter:
    @staticmethod
    def write(classfile: ClassFile) -> bytes: ...

# =============================================================================
# Model Layer
# =============================================================================

class RustLabel:
    def __init__(self) -> None: ...
    @staticmethod
    def named(name: str) -> RustLabel: ...
    @property
    def name(self) -> str | None: ...
    def __eq__(self, other: RustLabel) -> bool: ...  # type: ignore[override]
    def __hash__(self) -> int: ...

class RustExceptionHandler:
    @property
    def start(self) -> RustLabel: ...
    @property
    def end(self) -> RustLabel: ...
    @property
    def handler(self) -> RustLabel: ...
    @property
    def catch_type(self) -> str | None: ...

class RustStringListView:
    def __getitem__(self, index: int) -> str: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def to_list(self) -> list[str]: ...

class RustAttributeListView:
    def __getitem__(self, index: int) -> Any: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def to_list(self) -> list[Any]: ...

class RustCodeListView:
    def __getitem__(self, index: int) -> Any: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def to_list(self) -> list[Any]: ...

class RustCodeModel:
    @property
    def max_stack(self) -> int: ...
    @property
    def max_locals(self) -> int: ...
    @property
    def instructions(self) -> RustCodeListView: ...
    @property
    def exception_handlers(self) -> RustCodeListView: ...
    @property
    def line_numbers(self) -> RustCodeListView: ...
    @property
    def local_variables(self) -> RustCodeListView: ...
    @property
    def local_variable_types(self) -> RustCodeListView: ...
    @property
    def attributes(self) -> RustAttributeListView: ...
    @property
    def debug_info_state(self) -> str: ...
    @property
    def nested_attribute_layout(self) -> list[str]: ...

class RustFieldModel:
    def __init__(self, name: str, descriptor: str, access_flags: int) -> None: ...
    @property
    def access_flags(self) -> int: ...
    @access_flags.setter
    def access_flags(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def descriptor(self) -> str: ...
    @descriptor.setter
    def descriptor(self, value: str) -> None: ...
    @property
    def attributes(self) -> RustAttributeListView: ...

class RustFieldListView:
    def __getitem__(self, index: int) -> RustFieldModel: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[RustFieldModel]: ...
    def to_list(self) -> list[RustFieldModel]: ...

class RustMethodModel:
    def __init__(self, name: str, descriptor: str, access_flags: int) -> None: ...
    @property
    def access_flags(self) -> int: ...
    @access_flags.setter
    def access_flags(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def descriptor(self) -> str: ...
    @descriptor.setter
    def descriptor(self, value: str) -> None: ...
    @property
    def code(self) -> RustCodeModel | None: ...
    @property
    def attributes(self) -> RustAttributeListView: ...
    def set_raw_code(self, max_stack: int, max_locals: int, code_bytes: bytes) -> None: ...
    def set_prebuilt_code(self, code_body_bytes: bytes) -> None: ...

class RustMethodListView:
    def __getitem__(self, index: int) -> RustMethodModel: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[RustMethodModel]: ...
    def to_list(self) -> list[RustMethodModel]: ...

class RustConstantPoolBuilder:
    def __init__(self) -> None: ...
    def add_utf8(self, value: str) -> int: ...
    def add_class(self, name: str) -> int: ...
    def add_string(self, value: str) -> int: ...
    def add_integer(self, value: int) -> int: ...
    def add_long(self, high: int, low: int) -> int: ...
    def add_float_bits(self, raw_bits: int) -> int: ...
    def add_float(self, raw_bits: int) -> int: ...
    def add_double_bits(self, raw_bits: int) -> int: ...
    def add_double(self, high: int, low: int) -> int: ...
    def add_field_ref(self, owner: str, name: str, descriptor: str) -> int: ...
    def add_method_ref(self, owner: str, name: str, descriptor: str) -> int: ...
    def add_interface_method_ref(self, owner: str, name: str, descriptor: str) -> int: ...
    def add_fieldref(self, owner: str, name: str, descriptor: str) -> int: ...
    def add_methodref(self, owner: str, name: str, descriptor: str) -> int: ...
    def add_interface_methodref(self, owner: str, name: str, descriptor: str) -> int: ...
    def add_method_type(self, descriptor: str) -> int: ...
    def add_method_handle(self, reference_kind: int, reference_index: int) -> int: ...
    def add_invoke_dynamic(self, bootstrap_idx: int, name: str, descriptor: str) -> int: ...
    def add_dynamic(self, bootstrap_idx: int, name: str, descriptor: str) -> int: ...
    def resolve_utf8(self, index: int) -> str: ...
    def resolve_class_name(self, index: int) -> str: ...
    def count(self) -> int: ...
    def len(self) -> int: ...
    def raw_constant_pool(self) -> list[Any | None]: ...
    def checkpoint(self) -> int: ...
    def rollback(self, checkpoint: int) -> None: ...
    def find_integer(self, value: int) -> int | None: ...
    def find_float(self, raw_bits: int) -> int | None: ...
    def find_long(self, high: int, low: int) -> int | None: ...
    def find_double(self, high: int, low: int) -> int | None: ...
    def find_string(self, value: str) -> int | None: ...
    def find_class(self, name: str) -> int | None: ...
    def find_method_type(self, descriptor: str) -> int | None: ...
    def find_fieldref(self, owner: str, name: str, descriptor: str) -> int | None: ...
    def find_methodref(self, owner: str, name: str, descriptor: str) -> int | None: ...
    def find_interface_methodref(self, owner: str, name: str, descriptor: str) -> int | None: ...
    def find_method_handle(self, reference_kind: int, reference_index: int) -> int | None: ...
    def find_dynamic(self, bootstrap_method_attr_index: int, name: str, descriptor: str) -> int | None: ...

class RustMappingClassResolver:
    def __init__(self) -> None: ...
    @staticmethod
    def from_bytes(class_bytes_list: list[bytes]) -> RustMappingClassResolver: ...
    @staticmethod
    def from_models(models: list[RustClassModel]) -> RustMappingClassResolver: ...
    def resolve_class(self, name: str) -> Any | None: ...

class RustClassModel:
    @staticmethod
    def from_bytes(data: bytes) -> RustClassModel: ...
    def to_bytes(self) -> bytes: ...
    def to_bytes_with_options(
        self,
        recompute_frames: bool = False,
        resolver: RustMappingClassResolver | None = None,
        debug_info: str = "preserve",
    ) -> bytes: ...
    @property
    def entry_name(self) -> str: ...
    @property
    def original_byte_len(self) -> int: ...
    @property
    def version(self) -> tuple[int, int]: ...
    @version.setter
    def version(self, value: tuple[int, int]) -> None: ...
    @property
    def access_flags(self) -> int: ...
    @access_flags.setter
    def access_flags(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def super_name(self) -> str | None: ...
    @super_name.setter
    def super_name(self, value: str | None) -> None: ...
    @property
    def interfaces(self) -> RustStringListView: ...
    @interfaces.setter
    def interfaces(self, value: list[str]) -> None: ...
    @property
    def fields(self) -> RustFieldListView: ...
    @fields.setter
    def fields(self, value: list[RustFieldModel]) -> None: ...
    @property
    def methods(self) -> RustMethodListView: ...
    @methods.setter
    def methods(self, value: list[RustMethodModel]) -> None: ...
    @property
    def attributes(self) -> RustAttributeListView: ...
    @property
    def constant_pool(self) -> RustConstantPoolBuilder: ...
    @property
    def debug_info_state(self) -> str: ...

class RustClassMatcher:
    @staticmethod
    def named(name: str) -> RustClassMatcher: ...
    @staticmethod
    def name_matches(pattern: str) -> RustClassMatcher:
        """Match by regex against class name.  Raises ``ValueError`` for invalid patterns."""
        ...
    @staticmethod
    def access_all(flags: int) -> RustClassMatcher: ...
    @staticmethod
    def access_any(flags: int) -> RustClassMatcher: ...
    @staticmethod
    def is_package_private() -> RustClassMatcher: ...
    @staticmethod
    def extends(name: str) -> RustClassMatcher: ...
    @staticmethod
    def implements(name: str) -> RustClassMatcher: ...
    @staticmethod
    def version(major: int) -> RustClassMatcher: ...
    @staticmethod
    def version_at_least(major: int) -> RustClassMatcher: ...
    @staticmethod
    def version_below(major: int) -> RustClassMatcher: ...
    @staticmethod
    def any() -> RustClassMatcher: ...
    def __and__(self, other: RustClassMatcher) -> RustClassMatcher: ...
    def __or__(self, other: RustClassMatcher) -> RustClassMatcher: ...
    def __invert__(self) -> RustClassMatcher: ...

class RustFieldMatcher:
    @staticmethod
    def named(name: str) -> RustFieldMatcher: ...
    @staticmethod
    def name_matches(pattern: str) -> RustFieldMatcher:
        """Match by regex against field name.  Raises ``ValueError`` for invalid patterns."""
        ...
    @staticmethod
    def descriptor(desc: str) -> RustFieldMatcher: ...
    @staticmethod
    def descriptor_matches(pattern: str) -> RustFieldMatcher:
        """Match by regex against field descriptor.  Raises ``ValueError`` for invalid patterns."""
        ...
    @staticmethod
    def access_all(flags: int) -> RustFieldMatcher: ...
    @staticmethod
    def access_any(flags: int) -> RustFieldMatcher: ...
    @staticmethod
    def is_package_private() -> RustFieldMatcher: ...
    @staticmethod
    def any() -> RustFieldMatcher: ...
    def __and__(self, other: RustFieldMatcher) -> RustFieldMatcher: ...
    def __or__(self, other: RustFieldMatcher) -> RustFieldMatcher: ...
    def __invert__(self) -> RustFieldMatcher: ...

class RustMethodMatcher:
    @staticmethod
    def named(name: str) -> RustMethodMatcher: ...
    @staticmethod
    def name_matches(pattern: str) -> RustMethodMatcher:
        """Match by regex against method name.  Raises ``ValueError`` for invalid patterns."""
        ...
    @staticmethod
    def descriptor(desc: str) -> RustMethodMatcher: ...
    @staticmethod
    def descriptor_matches(pattern: str) -> RustMethodMatcher:
        """Match by regex against method descriptor.  Raises ``ValueError`` for invalid patterns."""
        ...
    @staticmethod
    def access_all(flags: int) -> RustMethodMatcher: ...
    @staticmethod
    def access_any(flags: int) -> RustMethodMatcher: ...
    @staticmethod
    def is_package_private() -> RustMethodMatcher: ...
    @staticmethod
    def has_code() -> RustMethodMatcher: ...
    @staticmethod
    def is_constructor() -> RustMethodMatcher: ...
    @staticmethod
    def is_static_initializer() -> RustMethodMatcher: ...
    @staticmethod
    def returns(descriptor: str) -> RustMethodMatcher: ...
    @staticmethod
    def any() -> RustMethodMatcher: ...
    def __and__(self, other: RustMethodMatcher) -> RustMethodMatcher: ...
    def __or__(self, other: RustMethodMatcher) -> RustMethodMatcher: ...
    def __invert__(self) -> RustMethodMatcher: ...

class RustClassTransform:
    @staticmethod
    def rename_class(name: str) -> RustClassTransform: ...
    @staticmethod
    def set_access_flags(flags: int) -> RustClassTransform: ...
    @staticmethod
    def add_access_flags(flags: int) -> RustClassTransform: ...
    @staticmethod
    def remove_access_flags(flags: int) -> RustClassTransform: ...
    @staticmethod
    def set_super_class(name: str) -> RustClassTransform: ...
    @staticmethod
    def add_interface(name: str) -> RustClassTransform: ...
    @staticmethod
    def remove_interface(name: str) -> RustClassTransform: ...
    @staticmethod
    def remove_method(name: str, descriptor: str | None = None) -> RustClassTransform: ...
    @staticmethod
    def remove_field(name: str, descriptor: str | None = None) -> RustClassTransform: ...
    @staticmethod
    def rename_method(from_name: str, to_name: str) -> RustClassTransform: ...
    @staticmethod
    def rename_field(from_name: str, to_name: str) -> RustClassTransform: ...
    @staticmethod
    def set_method_access_flags(name: str, flags: int) -> RustClassTransform: ...
    @staticmethod
    def set_field_access_flags(name: str, flags: int) -> RustClassTransform: ...
    @staticmethod
    def sequence(transforms: list[RustClassTransform]) -> RustClassTransform: ...

class RustCompiledPipeline:
    def apply(self, model: RustClassModel) -> None: ...
    def apply_all(self, models: list[RustClassModel]) -> None: ...

class RustPipeline:
    def __init__(self) -> None: ...
    def on_classes(self, matcher: RustClassMatcher, transform: RustClassTransform) -> None: ...
    def on_classes_custom(self, matcher: RustClassMatcher, callback: Callable[[RustClassModel], None]) -> None: ...
    def on_fields(
        self,
        field_matcher: RustFieldMatcher,
        transform: RustClassTransform,
        owner_matcher: RustClassMatcher | None = None,
    ) -> None: ...
    def on_fields_custom(
        self,
        field_matcher: RustFieldMatcher,
        callback: Callable[[RustClassModel], None],
        owner_matcher: RustClassMatcher | None = None,
    ) -> None: ...
    def on_methods(
        self,
        method_matcher: RustMethodMatcher,
        transform: RustClassTransform,
        owner_matcher: RustClassMatcher | None = None,
    ) -> None: ...
    def on_methods_custom(
        self,
        method_matcher: RustMethodMatcher,
        callback: Callable[[RustClassModel], None],
        owner_matcher: RustClassMatcher | None = None,
    ) -> None: ...
    def apply(self, model: RustClassModel) -> None: ...
    def apply_all(self, models: list[RustClassModel]) -> None: ...
    def compile(self) -> RustCompiledPipeline: ...
    def __len__(self) -> int: ...

def rewrite_archive_with_rust_transform(
    source_path: str | Path,
    transform: RustClassTransform | RustPipeline | RustCompiledPipeline,
    output_path: str | Path | None = None,
    recompute_frames: bool = False,
    resolver: RustMappingClassResolver | None = None,
    debug_info: str = "preserve",
) -> Path: ...

# =============================================================================
# Analysis
# =============================================================================

class RustDiagnostic:
    @property
    def severity(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def class_name(self) -> str | None: ...
    @property
    def field_name(self) -> str | None: ...
    @property
    def method_name(self) -> str | None: ...
    @property
    def method_descriptor(self) -> str | None: ...
    @property
    def attribute_name(self) -> str | None: ...
    @property
    def cp_index(self) -> int | None: ...
    @property
    def code_index(self) -> int | None: ...

def rust_verify_classfile(data: bytes, *, fail_fast: bool = False) -> list[RustDiagnostic]: ...
def rust_resolved_classfile(data: bytes) -> Any: ...
def rust_resolved_classmodel(model: RustClassModel) -> Any: ...
def rust_iter_superclasses(
    resolver: RustMappingClassResolver,
    class_name: str,
    *,
    include_self: bool = False,
) -> list[Any]: ...
def rust_iter_supertypes(
    resolver: RustMappingClassResolver,
    class_name: str,
    *,
    include_self: bool = False,
) -> list[Any]: ...
def rust_is_subtype(resolver: RustMappingClassResolver, class_name: str, super_name: str) -> bool: ...
def rust_common_superclass(resolver: RustMappingClassResolver, left: str, right: str) -> str: ...
def rust_find_overridden_methods(
    resolver: RustMappingClassResolver,
    class_name: str,
    method_name: str,
    method_descriptor: str,
    access_flags: int,
) -> list[Any]: ...
def rust_verify_classmodel(
    model: RustClassModel,
    resolver: RustMappingClassResolver | None = None,
    *,
    fail_fast: bool = False,
) -> list[RustDiagnostic]: ...

# =============================================================================
# Attribute Wrapper Types — Verification Type Info
# =============================================================================

class TopVariableInfo:
    @property
    def tag(self) -> Any: ...

class IntegerVariableInfo:
    @property
    def tag(self) -> Any: ...

class FloatVariableInfo:
    @property
    def tag(self) -> Any: ...

class DoubleVariableInfo:
    @property
    def tag(self) -> Any: ...

class LongVariableInfo:
    @property
    def tag(self) -> Any: ...

class NullVariableInfo:
    @property
    def tag(self) -> Any: ...

class UninitializedThisVariableInfo:
    @property
    def tag(self) -> Any: ...

class ObjectVariableInfo:
    @property
    def tag(self) -> Any: ...
    @property
    def cpool_index(self) -> int: ...

class UninitializedVariableInfo:
    @property
    def tag(self) -> Any: ...
    @property
    def offset(self) -> int: ...

# =============================================================================
# Attribute Wrapper Types — Stack Map Frame Info
# =============================================================================

class SameFrameInfo:
    @property
    def frame_type(self) -> int: ...

class SameLocals1StackItemFrameInfo:
    @property
    def frame_type(self) -> int: ...
    @property
    def stack(self) -> Any: ...

class SameLocals1StackItemFrameExtendedInfo:
    @property
    def frame_type(self) -> int: ...
    @property
    def offset_delta(self) -> int: ...
    @property
    def stack(self) -> Any: ...

class ChopFrameInfo:
    @property
    def frame_type(self) -> int: ...
    @property
    def offset_delta(self) -> int: ...

class SameFrameExtendedInfo:
    @property
    def frame_type(self) -> int: ...
    @property
    def offset_delta(self) -> int: ...

class AppendFrameInfo:
    @property
    def frame_type(self) -> int: ...
    @property
    def offset_delta(self) -> int: ...
    @property
    def locals(self) -> list[Any]: ...

class FullFrameInfo:
    @property
    def frame_type(self) -> int: ...
    @property
    def offset_delta(self) -> int: ...
    @property
    def number_of_locals(self) -> int: ...
    @property
    def locals(self) -> list[Any]: ...
    @property
    def number_of_stack_items(self) -> int: ...
    @property
    def stack(self) -> list[Any]: ...

# =============================================================================
# Attribute Wrapper Types — Simple Entry Types
# =============================================================================

class LineNumberInfo:
    @property
    def start_pc(self) -> int: ...
    @property
    def line_number(self) -> int: ...

class LocalVariableInfo:
    @property
    def start_pc(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def name_index(self) -> int: ...
    @property
    def descriptor_index(self) -> int: ...
    @property
    def index(self) -> int: ...

class LocalVariableTypeInfo:
    @property
    def start_pc(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def name_index(self) -> int: ...
    @property
    def signature_index(self) -> int: ...
    @property
    def index(self) -> int: ...

class InnerClassInfo:
    @property
    def inner_class_info_index(self) -> int: ...
    @property
    def outer_class_info_index(self) -> int: ...
    @property
    def inner_name_index(self) -> int: ...
    @property
    def inner_class_access_flags(self) -> Any: ...

# =============================================================================
# Attribute Wrapper Types — Annotation Sub-types
# =============================================================================

class ConstValueInfo:
    @property
    def const_value_index(self) -> int: ...

class EnumConstantValueInfo:
    @property
    def type_name_index(self) -> int: ...
    @property
    def const_name_index(self) -> int: ...

class ClassInfoValueInfo:
    @property
    def class_info_index(self) -> int: ...

class ArrayValueInfo:
    @property
    def num_values(self) -> int: ...
    @property
    def values(self) -> list[Any]: ...

class ElementValueInfo:
    @property
    def tag(self) -> str: ...
    @property
    def value(self) -> Any: ...

class ElementValuePairInfo:
    @property
    def element_name_index(self) -> int: ...
    @property
    def element_value(self) -> Any: ...

class AnnotationInfo:
    @property
    def type_index(self) -> int: ...
    @property
    def num_element_value_pairs(self) -> int: ...
    @property
    def element_value_pairs(self) -> list[Any]: ...

class ParameterAnnotationInfo:
    @property
    def num_annotations(self) -> int: ...
    @property
    def annotations(self) -> list[Any]: ...

# =============================================================================
# Attribute Wrapper Types — Type Annotation Sub-types
# =============================================================================

class TypeParameterTargetInfo:
    @property
    def type_parameter_index(self) -> int: ...

class SupertypeTargetInfo:
    @property
    def supertype_index(self) -> int: ...

class TypeParameterBoundTargetInfo:
    @property
    def type_parameter_index(self) -> int: ...
    @property
    def bound_index(self) -> int: ...

class EmptyTargetInfo: ...

class FormalParameterTargetInfo:
    @property
    def formal_parameter_index(self) -> int: ...

class ThrowsTargetInfo:
    @property
    def throws_type_index(self) -> int: ...

class TableInfo:
    @property
    def start_pc(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def index(self) -> int: ...

class LocalvarTargetInfo:
    @property
    def table_length(self) -> int: ...
    @property
    def table(self) -> list[Any]: ...

class CatchTargetInfo:
    @property
    def exception_table_index(self) -> int: ...

class OffsetTargetInfo:
    @property
    def offset(self) -> int: ...

class TypeArgumentTargetInfo:
    @property
    def offset(self) -> int: ...
    @property
    def type_argument_index(self) -> int: ...

class PathInfo:
    @property
    def type_path_kind(self) -> Any: ...
    @property
    def type_argument_index(self) -> int: ...

class TypePathInfo:
    @property
    def path_length(self) -> int: ...
    @property
    def path(self) -> list[Any]: ...

class TypeAnnotationInfo:
    @property
    def target_type(self) -> Any: ...
    @property
    def target_info(self) -> Any: ...
    @property
    def target_path(self) -> Any: ...
    @property
    def type_index(self) -> int: ...
    @property
    def num_element_value_pairs(self) -> int: ...
    @property
    def element_value_pairs(self) -> list[Any]: ...

# =============================================================================
# Attribute Wrapper Types — Bootstrap, Method Parameter, Module Sub-types
# =============================================================================

class BootstrapMethodInfo:
    @property
    def bootstrap_method_ref(self) -> int: ...
    @property
    def num_boostrap_arguments(self) -> int: ...
    @property
    def boostrap_arguments(self) -> list[int]: ...

class MethodParameterInfo:
    @property
    def name_index(self) -> int: ...
    @property
    def access_flags(self) -> Any: ...

class RequiresInfo:
    @property
    def requires_index(self) -> int: ...
    @property
    def requires_flag(self) -> Any: ...
    @property
    def requires_version_index(self) -> int: ...

class ExportInfo:
    @property
    def exports_index(self) -> int: ...
    @property
    def exports_flags(self) -> Any: ...
    @property
    def exports_to_count(self) -> int: ...
    @property
    def exports_to_index(self) -> list[int]: ...

class OpensInfo:
    @property
    def opens_index(self) -> int: ...
    @property
    def opens_flags(self) -> Any: ...
    @property
    def opens_to_count(self) -> int: ...
    @property
    def opens_to_index(self) -> list[int]: ...

class ProvidesInfo:
    @property
    def provides_index(self) -> int: ...
    @property
    def provides_with_count(self) -> int: ...
    @property
    def provides_with_index(self) -> list[int]: ...

class RecordComponentInfo:
    @property
    def name_index(self) -> int: ...
    @property
    def descriptor_index(self) -> int: ...
    @property
    def attributes_count(self) -> int: ...
    @property
    def attributes(self) -> list[Any]: ...

# =============================================================================
# Attribute Wrapper Types — Top-Level Attribute Classes
# =============================================================================

class StackMapTableAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def number_of_entries(self) -> int: ...
    @property
    def entries(self) -> list[Any]: ...

class InnerClassesAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def number_of_classes(self) -> int: ...
    @property
    def classes(self) -> list[Any]: ...

class EnclosingMethodAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def class_index(self) -> int: ...
    @property
    def method_index(self) -> int: ...

class SyntheticAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...

class DeprecatedAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...

class LineNumberTableAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def line_number_table_length(self) -> int: ...
    @property
    def line_number_table(self) -> list[Any]: ...

class LocalVariableTableAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def local_variable_table_length(self) -> int: ...
    @property
    def local_variable_table(self) -> list[Any]: ...

class LocalVariableTypeTableAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def local_variable_type_table_length(self) -> int: ...
    @property
    def local_variable_type_table(self) -> list[Any]: ...

class RuntimeVisibleAnnotationsAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def num_annotations(self) -> int: ...
    @property
    def annotations(self) -> list[Any]: ...

class RuntimeInvisibleAnnotationsAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def num_annotations(self) -> int: ...
    @property
    def annotations(self) -> list[Any]: ...

class RuntimeVisibleParameterAnnotationsAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def num_parameters(self) -> int: ...
    @property
    def parameter_annotations(self) -> list[Any]: ...

class RuntimeInvisibleParameterAnnotationsAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def num_parameters(self) -> int: ...
    @property
    def parameter_annotations(self) -> list[Any]: ...

class RuntimeVisibleTypeAnnotationsAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def num_annotations(self) -> int: ...
    @property
    def annotations(self) -> list[Any]: ...

class RuntimeInvisibleTypeAnnotationsAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def num_annotations(self) -> int: ...
    @property
    def annotations(self) -> list[Any]: ...

class AnnotationDefaultAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def default_value(self) -> Any: ...

class BootstrapMethodsAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def num_bootstrap_methods(self) -> int: ...
    @property
    def bootstrap_methods(self) -> list[Any]: ...

class MethodParametersAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def parameters_count(self) -> int: ...
    @property
    def parameters(self) -> list[Any]: ...

class ModuleAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def module_name_index(self) -> int: ...
    @property
    def module_flags(self) -> Any: ...
    @property
    def module_version_index(self) -> int: ...
    @property
    def requires_count(self) -> int: ...
    @property
    def requires(self) -> list[Any]: ...
    @property
    def exports_count(self) -> int: ...
    @property
    def exports(self) -> list[Any]: ...
    @property
    def opens_count(self) -> int: ...
    @property
    def opens(self) -> list[Any]: ...
    @property
    def uses_count(self) -> int: ...
    @property
    def uses_index(self) -> list[int]: ...
    @property
    def provides_count(self) -> int: ...
    @property
    def provides(self) -> list[Any]: ...

class ModulePackagesAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def package_count(self) -> int: ...
    @property
    def package_index(self) -> list[int]: ...

class ModuleMainClassAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def main_class_index(self) -> int: ...

class NestHostAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def host_class_index(self) -> int: ...

class NestMembersAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def number_of_classes(self) -> int: ...
    @property
    def classes(self) -> list[int]: ...

class RecordAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def components_count(self) -> int: ...
    @property
    def components(self) -> list[Any]: ...

class PermittedSubclassesAttr:
    @property
    def attribute_name_index(self) -> int: ...
    @property
    def attribute_length(self) -> int: ...
    @property
    def number_of_classes(self) -> int: ...
    @property
    def classes(self) -> list[int]: ...

# =============================================================================
# Module-Level Functions
# =============================================================================

def backend_info() -> tuple[str, str, list[str]]: ...
