from enum import Enum, IntEnum, IntFlag

from . import attributes, constant_pool

MAGIC = 0xCAFEBABE


class ModuleAccessFlag(IntFlag):
    OPEN = 0x0020
    SYNTHETIC = 0x1000
    MANDATED = 0x8000


class ModuleRequiresAccessFlag(IntFlag):
    TRANSITIVE = 0x0020
    STATIC_PHASE = 0x0040
    SYNTHETIC = 0x1000
    MANDATED = 0x8000


class ModuleExportsAccessFlag(IntFlag):
    SYNTHETIC = 0x1000
    MANDATED = 0x8000


class ModuleOpensAccessFlag(IntFlag):
    SYNTHETIC = 0x1000
    MANDATED = 0x8000


class ClassAccessFlag(IntFlag):
    PUBLIC = 0x0001
    FINAL = 0x0010
    SUPER = 0x0020
    INTERFACE = 0x0200
    ABSTRACT = 0x0400
    SYNTHETIC = 0x1000
    ANNOTATION = 0x2000
    ENUM = 0x4000
    MODULE = 0x8000


class NestedClassAccessFlag(IntFlag):
    PUBLIC = 0x0001
    PRIVATE = 0x0002
    PROTECTED = 0x0004
    STATIC = 0x0008
    FINAL = 0x0010
    INTERFACE = 0x0200
    ABSTRACT = 0x0400
    SYNTHETIC = 0x1000
    ANNOTATION = 0x2000
    ENUM = 0x4000


class MethodAccessFlag(IntFlag):
    PUBLIC = 0x0001
    PRIVATE = 0x0002
    PROTECTED = 0x0004
    STATIC = 0x0008
    FINAL = 0x0010
    SYNCHRONIZED = 0x0020
    BRIDGE = 0x0040
    VARARGS = 0x0080
    NATIVE = 0x0100
    ABSTRACT = 0x0400
    STRICT = 0x0800
    SYNTHETIC = 0x1000


class MethodParameterAccessFlag(IntFlag):
    FINAL = 0x0010
    SYNTHETIC = 0x1000
    MANDATED = 0x8000


class FieldAccessFlag(IntFlag):
    PUBLIC = 0x0001
    PRIVATE = 0x0002
    PROTECTED = 0x0004
    STATIC = 0x0008
    FINAL = 0x0010
    VOLATILE = 0x0040
    TRANSIENT = 0x0080
    SYNTHETIC = 0x1000
    ENUM = 0x4000


class FieldType(Enum):
    BYTE = "B"
    CHAR = "C"
    DOUBLE = "D"
    FLOAT = "F"
    INT = "I"
    LONG = "J"
    REF = "L"
    SHORT = "S"
    BOOL = "Z"
    ARRAY = "["


class TargetType(IntEnum):
    TYPE_PARAMETER_GENERIC_CLASS_OR_INTERFACE = 0x00
    TYPE_PARAMETER_GENERIC_METHOD_OR_CONSTRUCTOR = 0x01
    SUPERTYPE = 0x10
    TYPE_PARAMETER_BOUND_GENERIC_CLASS_OR_INTERFACE = 0x11
    TYPE_PARAMETER_BOUND_GENERIC_METHOD_OR_CONSTRUCTOR = 0x12
    TYPE_IN_FIELD_OR_RECORD = 0x13
    RETURN_OR_OBJECT_TYPE = 0x14
    RECEIVER_TYPE_METHOD_OR_CONSTRUCTOR = 0x15
    FORMAL_PARAMETER_METHOD_CONSTRUCTOR_OR_LAMBDA = 0x16
    TYPE_THROWS = 0x17
    TYPE_LOCAL_VARIABLE = 0x40
    TYPE_RESOURCE_VARIABLE = 0x41
    TYPE_EXCEPTION_PARAMETER = 0x42
    TYPE_INSTANCEOF = 0x43
    TYPE_NEW = 0x44
    TYPE_METHOD_NEW = 0x45
    TYPE_METHOD_IDENTIFIER = 0x46
    TYPE_CAST = 0x47
    TYPE_GENERIC_CONSTRUCTOR = 0x48
    TYPE_GENERIC_METHOD = 0x49
    TYPE_GENERIC_CONSTRUCTOR_NEW = 0x4A
    TYPE_GENERIC_METHOD_IDENTIFIER = 0x4B


class TargetInfoType(Enum):
    TYPE_PARAMETER = (
        TargetType.TYPE_PARAMETER_GENERIC_CLASS_OR_INTERFACE,
        TargetType.TYPE_PARAMETER_GENERIC_METHOD_OR_CONSTRUCTOR,
    )
    SUPERTYPE = (TargetType.SUPERTYPE,)
    TYPE_PARAMETER_BOUND = (
        TargetType.TYPE_PARAMETER_BOUND_GENERIC_CLASS_OR_INTERFACE,
        TargetType.TYPE_PARAMETER_BOUND_GENERIC_METHOD_OR_CONSTRUCTOR,
    )
    EMPTY = (
        TargetType.TYPE_IN_FIELD_OR_RECORD,
        TargetType.RETURN_OR_OBJECT_TYPE,
        TargetType.RECEIVER_TYPE_METHOD_OR_CONSTRUCTOR,
    )
    FORMAL_PARAMETER = (TargetType.FORMAL_PARAMETER_METHOD_CONSTRUCTOR_OR_LAMBDA,)
    THROWS = (TargetType.TYPE_THROWS,)
    LOCALVAR = (TargetType.TYPE_LOCAL_VARIABLE, TargetType.TYPE_RESOURCE_VARIABLE)
    CATCH = (TargetType.TYPE_EXCEPTION_PARAMETER,)
    OFFSET = (
        TargetType.TYPE_INSTANCEOF,
        TargetType.TYPE_NEW,
        TargetType.TYPE_METHOD_NEW,
        TargetType.TYPE_METHOD_IDENTIFIER,
    )
    TYPE_ARGUMENT = (
        TargetType.TYPE_CAST,
        TargetType.TYPE_GENERIC_CONSTRUCTOR,
        TargetType.TYPE_GENERIC_METHOD,
        TargetType.TYPE_GENERIC_CONSTRUCTOR_NEW,
        TargetType.TYPE_GENERIC_METHOD_IDENTIFIER,
    )


class TypePathKind(IntEnum):
    ARRAY_TYPE = 0
    NESTED_TYPE = 1
    WILDCARD_TYPE = 2
    PARAMETERIZED_TYPE = 3


class VerificationType(IntEnum):
    TOP = 0
    INTEGER = 1
    FLOAT = 2
    DOUBLE = 3
    LONG = 4
    NULL = 5
    UNINITIALIZED_THIS = 6
    OBJECT = 7
    UNINITIALIZED = 8
