"""Declarative transform helpers for pytecode.

Matchers, transforms, and pipeline builder for class manipulation::

    from pytecode.transforms import PipelineBuilder, class_named, rename_class

    p = (
        PipelineBuilder()
        .on_classes(class_named("com/example/Foo"), rename_class("com/example/Bar"))
        .build()
    )
"""

from __future__ import annotations

from .._rust import (
    RustClassMatcher,
    RustClassTransform,
    RustCompiledPipeline,
    RustFieldMatcher,
    RustMethodMatcher,
    RustPipeline,
)
from .class_transforms import (
    add_access_flags,
    add_interface,
    remove_access_flags,
    remove_field,
    remove_interface,
    remove_method,
    rename_class,
    rename_field,
    rename_method,
    sequence,
    set_access_flags,
    set_field_access_flags,
    set_method_access_flags,
    set_super_class,
)
from .matchers import (
    class_access,
    class_access_any,
    class_is_abstract,
    class_is_annotation,
    class_is_enum,
    class_is_final,
    class_is_interface,
    class_is_module,
    class_is_package_private,
    class_is_public,
    class_is_synthetic,
    class_name_matches,
    class_named,
    class_version,
    class_version_at_least,
    class_version_below,
    extends,
    field_access,
    field_access_any,
    field_descriptor,
    field_descriptor_matches,
    field_is_enum_constant,
    field_is_final,
    field_is_package_private,
    field_is_private,
    field_is_protected,
    field_is_public,
    field_is_static,
    field_is_synthetic,
    field_is_transient,
    field_is_volatile,
    field_name_matches,
    field_named,
    has_code,
    implements,
    is_constructor,
    is_static_initializer,
    method_access,
    method_access_any,
    method_descriptor,
    method_descriptor_matches,
    method_is_abstract,
    method_is_bridge,
    method_is_final,
    method_is_native,
    method_is_package_private,
    method_is_private,
    method_is_protected,
    method_is_public,
    method_is_static,
    method_is_strict,
    method_is_synchronized,
    method_is_synthetic,
    method_is_varargs,
    method_name_matches,
    method_named,
    method_returns,
)
from .pipeline import PipelineBuilder, RustPipelineBuilder

# Unprefixed aliases for Rust-native types
ClassMatcher = RustClassMatcher
FieldMatcher = RustFieldMatcher
MethodMatcher = RustMethodMatcher
ClassTransform = RustClassTransform
Pipeline = RustPipeline
CompiledPipeline = RustCompiledPipeline

__all__ = [
    # Canonical (unprefixed) names
    "ClassMatcher",
    "ClassTransform",
    "CompiledPipeline",
    "FieldMatcher",
    "MethodMatcher",
    "Pipeline",
    "PipelineBuilder",
    # Backward-compat prefixed names
    "RustClassMatcher",
    "RustClassTransform",
    "RustCompiledPipeline",
    "RustFieldMatcher",
    "RustMethodMatcher",
    "RustPipeline",
    "RustPipelineBuilder",
    # Matcher factories
    "add_access_flags",
    "add_interface",
    "class_access",
    "class_access_any",
    "class_is_abstract",
    "class_is_annotation",
    "class_is_enum",
    "class_is_final",
    "class_is_interface",
    "class_is_module",
    "class_is_package_private",
    "class_is_public",
    "class_is_synthetic",
    "class_name_matches",
    "class_named",
    "class_version",
    "class_version_at_least",
    "class_version_below",
    "extends",
    "field_access",
    "field_access_any",
    "field_descriptor",
    "field_descriptor_matches",
    "field_is_enum_constant",
    "field_is_final",
    "field_is_package_private",
    "field_is_private",
    "field_is_protected",
    "field_is_public",
    "field_is_static",
    "field_is_synthetic",
    "field_is_transient",
    "field_is_volatile",
    "field_name_matches",
    "field_named",
    "has_code",
    "implements",
    "is_constructor",
    "is_static_initializer",
    "method_access",
    "method_access_any",
    "method_descriptor",
    "method_descriptor_matches",
    "method_is_abstract",
    "method_is_bridge",
    "method_is_final",
    "method_is_native",
    "method_is_package_private",
    "method_is_private",
    "method_is_protected",
    "method_is_public",
    "method_is_static",
    "method_is_strict",
    "method_is_synchronized",
    "method_is_synthetic",
    "method_is_varargs",
    "method_name_matches",
    "method_named",
    "method_returns",
    "remove_access_flags",
    "remove_field",
    "remove_interface",
    "remove_method",
    "rename_class",
    "rename_field",
    "rename_method",
    "sequence",
    "set_access_flags",
    "set_field_access_flags",
    "set_method_access_flags",
    "set_super_class",
]
